
version: '3'
services:
  web:
    build: ./web
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017  # Use an environment variable for the connection string

  db:
    image: mongo  # Use the official MongoDB image
    ports:
      - "27017:27017"
